apiVersion: apps/v1
kind: Deployment
metadata: 
  name: authorization-deployment
  labels: 
    app: AuthorizationService
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: AuthorizationService
  template:
    metadata:
      labels:
        app: AuthorizationService
    spec:
      containers: 
        - name: authorizationservice
          image: authorizationacr.azurecr.io/buildandpush:latest
          ports: 
            - containerPort: 8080
      imagePullSecrets: 
        - name: authorizationservicesvcsecret

---

apiVersion: v1
kind: Service
metadata:
  name: authorizationservicesvc
spec:
  type: LoadBalancer
  ports: 
    - port: 80
  selector:
    app: AuthorizationService
